create-project: auto-create Github repo for project.

diff --git a/utilities/.local/bin/create-project b/utilities/.local/bin/create-project
--- a/utilities/.local/bin/create-project
+++ b/utilities/.local/bin/create-project
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 source $HOME/.local/share/js-shell-lib/tui.sh
 
 TEMPLATE_HOME="$HOME/projects/project-templates"
@@ -26,6 +28,14 @@ latest_directory() {
     /bin/ls -1ct "$1" | head -1
 }
 
+create_github_repo() {
+    pushd "${project_dir}" || die "Cannot enter ${project_dir} to initialize git."
+    git add .
+    git commit -m "Initial commit"
+    gh repo create "${project_name}" --private --source . --push
+    popd || die "Popd failed."
+}
+
 main() {
     local template_name="$1"
     if [ -z "${template_name}" ]; then
@@ -39,9 +49,12 @@ main() {
     echo "Initializing Git..."
     local project_dir
     project_dir="${PROJECT_HOME}/$(latest_directory "${PROJECT_HOME}")"
+    local project_name
+    project_name=$(basename "${project_dir}")
     pushd "${project_dir}" || die "Cannot enter ${project_dir} to initialize git."
     git init
     popd || die "Popd failed."
+    tui_confirm "Do you want to create a GitHub repository '${project_name}'?" && create_github_repo
     tui_confirm "Do you want to edit the project?" && edit-project "${project_dir}"
 }
 
